specUri: github.com/lovethedrake/drakespec
specVersion: v0.1.0

snippets:

  baseDemoContainer: &baseDemoContainer
    name: demo
    image: debian:stretch

jobs:

  foo:
    containers:
    - <<: *baseDemoContainer
      command: echo foo

  bar:
    containers:
    - <<: *baseDemoContainer
      command: echo bar

pipelines:

  ci:
    triggers:
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        checkSuiteRequest:
          branches:
            only:
            - /.*/
    jobs:
    - name: foo
    - name: bar
      dependencies:
      - foo
