version: v1.0.0

baseDemoContainer: &baseDemoContainer
  name: demo
  image: debian:stretch

jobs:

  foo:
    containers:
    - <<: *baseDemoContainer
      command: echo foo

  bar:
    containers:
    - <<: *baseDemoContainer
      command: echo bar

pipelines:

  test:
    criteria:
      branches:
        ignore:
        - master
        - gh-pages
    stages:
    - jobs:
      - foo
      - bar

  master:
    criteria:
      branches:
        only:
        - master
    stages:
    - jobs:
      - foo
      - bar

  release:
    criteria:
      tags:
        only:
        - /v[0-9]+(\.[0-9]+)*(\-.+)?/
    stages:
    - jobs:
      - foo
      - bar
